Implement notarisation to release script

diff --git a/release b/release
--- a/release
+++ b/release
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# Exit on error
+trap 'exit' ERR
+
 # Colours
 reset=$(tput sgr0)
 bold=$(tput bold)
@@ -8,10 +11,8 @@ blue=$(tput setaf 4)
 app='Phoenix'
 sign_update="$PWD/Pods/Sparkle/bin/sign_update"
 
-# Exit on error
-trap 'exit' ERR
-
 # Unset arguments
+unset username
 unset code_sign_identity
 unset dsa_signature_key_path
 unset output_directory
@@ -20,9 +21,10 @@ unset output_directory
 
 help() {
   echo >&2 "\
-${bold}Usage:${reset} $(basename $0) -s code-sign-identity -d dsa-signature-key-path -o output-directory
+${bold}Usage:${reset} $(basename $0) -u username -s code-sign-identity -d dsa-signature-key-path -o output-directory
 
 Arguments:
+  -u username               Apple Developer username for notarisation, password is obtained from keychain item “AC_PASSWORD”
   -s code-sign-identity     used to sign the app
   -d dsa-signature-key-path used to create the DSA-signature
   -o output-directory       where the app archive is created"
@@ -40,26 +42,21 @@ describe() {
   echo -e "\n${bold}${blue}${1}${reset}\n"
 }
 
+get_property() {
+  /usr/libexec/PlistBuddy -c "Print $1" "$2"
+}
+
 get_build_setting() {
   xcodebuild -showBuildSettings | grep "$1" | tr -d "$1 = "
 }
 
 # Parse arguments
-while getopts ':s:d:o:' opt; do
-
+while getopts 'u:s:d:o:' opt; do
   case $opt in
-
-    s)
-      code_sign_identity=$OPTARG
-    ;;
-
-    d)
-      dsa_signature_key_path=$OPTARG
-    ;;
-
-    o)
-      output_directory=$OPTARG
-    ;;
+    u) username=$OPTARG;;
+    s) code_sign_identity=$OPTARG;;
+    d) dsa_signature_key_path=$OPTARG;;
+    o) output_directory=$OPTARG;;
 
     :)
       missing_argument $OPTARG
@@ -70,13 +67,11 @@ while getopts ':s:d:o:' opt; do
       help
       exit 1
     ;;
-
   esac
-
 done
 
 # Invalid arguments
-if [ ! "$code_sign_identity" ] || [ ! "$dsa_signature_key_path" ] || [ ! "$output_directory" ]; then
+if [ ! "$username" ] || [ ! "$code_sign_identity" ] || [ ! "$dsa_signature_key_path" ] || [ ! "$output_directory" ]; then
   help
   exit 1
 fi
@@ -97,6 +92,9 @@ fi
 
 version=$(get_build_setting 'MARKETING_VERSION')
 build_number=$(get_build_setting 'CURRENT_PROJECT_VERSION')
+notarisation_archive="phoenix-$version.zip"
+notarisation_upload_plist='notarisation-upload.plist'
+notarisation_info_plist='notarisation-info.plist'
 archive="phoenix-$version.tar.gz"
 
 if [ -f "$output_directory/$archive" ]; then
@@ -117,9 +115,53 @@ xcodebuild -workspace $app.xcworkspace \
 
 describe 'Verifying signed app...'
 
-cd build/Release
+cd build/Release/
 codesign --verbose=4 --verify $app.app
 spctl --verbose=4 --assess --type execute $app.app
+
+# Notarise app
+
+describe 'Notarising app...'
+
+echo 'Creating archive for notarisation...'
+ditto -c -k --keepParent $app.app $notarisation_archive
+
+echo 'Uploading archive to notarisation service...'
+xcrun altool --notarize-app \
+             --primary-bundle-id 'org.khirviko.Phoenix' \
+             --username $username \
+             --password '@keychain:AC_PASSWORD' \
+             --file $notarisation_archive \
+             --output-format xml \
+             > $notarisation_upload_plist
+
+notarisation_request_uuid=$(get_property 'notarization-upload:RequestUUID' $notarisation_upload_plist)
+echo "Uploaded. Request is “"$notarisation_request_uuid"”."
+
+while :
+do
+  xcrun altool --notarization-info $notarisation_request_uuid \
+               -u $username \
+               -p '@keychain:AC_PASSWORD' \
+               --output-format xml \
+               > $notarisation_info_plist
+
+  notarisation_status=$(get_property 'notarization-info:Status' $notarisation_info_plist)
+  if [ "$notarisation_status" = 'success' ]; then
+    notarisation_log=$(get_property 'notarization-info:LogFileURL' $notarisation_info_plist)
+    echo "Notarisation succeeded. Log: $notarisation_log"
+    break
+  fi
+
+  echo "Current status is “"$notarisation_status"”. Waiting..."
+  sleep 30
+done
+
+# Staple app
+
+describe 'Stapling app...'
+
+xcrun stapler staple $app.app
 
 # Archive app
 
